// <auto-generated />
namespace vclass_clone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class discssioninit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(discssioninit));
        
        string IMigrationMetadata.Id
        {
            get { return "202408171926585_discssion init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
