// <auto-generated />
namespace vclass_clone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class model_new_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(model_new_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "202408041258557_model_new_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
