// <auto-generated />
namespace vclass_clone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class update_course_assignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_course_assignment));
        
        string IMigrationMetadata.Id
        {
            get { return "202409071009079_update_course_assignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
