// <auto-generated />
namespace vclass_clone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class login_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(login_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202409071741186_login_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
